---
blank_issues_enabled: false
contact_links:
  - name: Creating animation from Design to SwiftUI Community Support
    url: https://github.com/developer-academy-unina/Workshop-Creating-animation-from-Design-to-SwiftUI/discussions
    about: Please ask and answer questions here.
